Add Campus Support Page
osg-htc/osg-htc.github.io pull request #125
Opened 2023-05-15 16:07 UTC by CannonLock

2023-05-21 21:25 UTC, osg-cat requested changes
I made significant content changes (which was my plan all along), and otherwise left a couple questions. When these changes are available in preview mode, I’d like Christina to take a quick look, too, if she has time — I can coordinate that if you like.

2023-05-21 21:25 UTC, osg-cat commented on campus/support.html
> +<h1 class="mini-bar">{{ page.title }}</h1>
Why this `mini-bar` class? It looks odd and I don’t see it on other pages. Unless there’s good reason for it, I’d like to drop the class.

2023-05-22 15:29 UTC, ChristinaLK commented on _includes/layout/header.html
> +                            <a class="dropdown-item" href="{{ '/campus/support.html' | relative_url }}">Support</a>
@osg-cat I don't think there *is* an index page for the different headings on the website.

2023-05-22 16:38 UTC, osg-cat commented
I am ok with it looking a bit empty, if the alternative is “empty” images that do not contribute to the message. The emptiness will be pressure on us to add meaningful content.
But if y’all really want pictures, go ahead!

2023-05-22 17:13 UTC, CannonLock commented
I think images would be good as long as they add value to that page, unfortunately I cannot think of any such images. @ChristinaLK Do you have any ideas?

2023-05-24 15:37 UTC, CannonLock commented
@osg-cat I made your changes to the header, is there any other changes you would like made before I merge?

2023-05-24 16:50 UTC, osg-cat commented
Let’s just get it up and we can tweak as needed.

2023-05-24 17:14 UTC, merged

2023-05-24 17:53 UTC, osg-cat commented
Looks great, thanks @CannonLock!